//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int IntId { get; set; }
        public string StrUsername { get; set; }
        public string StrEmail { get; set; }
        public string StrPassword { get; set; }
        public string StrContactNumber { get; set; }
        public string StrAddress { get; set; }
        public string StrType { get; set; }
    }
}
